<?php

namespace solver\solverBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * probleme_problemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class probleme_problemeRepository extends EntityRepository
{

}