<?php

namespace solver\solverBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * solutionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class solutionsRepository extends EntityRepository
{
}