<?php

namespace solver\solverBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * solving_logRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class solving_logRepository extends EntityRepository
{
    /**
     * compte les occurence d'un problème aval dans la table des logs
     * @param type $id 
     */
    public function compteOccurencesAval($id){
        $em=$this->_em;
                
        $query="SELECT COUNT (s.id) ".
               "FROM solver\solverBundle\Entity\solving_log s ".
               "WHERE s.problemeaval=".$id;
        
        return $em->createQuery($query)->getSingleScalarResult();                
    }
    
    public function compteOccurencesAmont($id){
        $em=$this->_em;
                
        $query="SELECT COUNT (s.id) ".
               "FROM solver\solverBundle\Entity\solving_log s ".
               "WHERE s.problemeamont=".$id;
        
        return $em->createQuery($query)->getSingleScalarResult();                
    }
    
    public function compteOccurencesAssociationProblemes($idAval, $idAmont){
        $em=$this->_em;
                
        $query="SELECT COUNT (s.id) ".
               "FROM solver\solverBundle\Entity\solving_log s ".
               "WHERE s.problemeaval=".$idAval." AND s.problemeamont=".$idAmont;
        
        return $em->createQuery($query)->getSingleScalarResult();                
    }
    
   public function TauxUtilisationProblemes($idAval, $idAmont){
        $em=$this->_em;
                
        $query="SELECT COUNT (s.id) ".
               "FROM solver\solverBundle\Entity\solving_log s ".
               "WHERE s.problemeaval=".$idAval." AND s.problemeamont=".$idAmont;
        
        return $em->createQuery($query)->getSingleScalarResult();                
    }
}